version: "3.1"
services:
  balancer:
  build: ./Balancer
    restart: always
    ports:
      - "5005:5005"
  server1:
    build: ./Server1
    restart: always
    ports:
      - "5006:5006"
  server2:
    build: ./Server2
    restart: always
    ports:
      - "5007:5007"
  server3:
    build: ./Server3
    restart: always
    ports:
      - "5008:5008"