version: "3.1"
services:
  balancer:
    build: ./Balancer
    restart: always
    ports:
      - "5005:5005"
    networks:
      service_network:
        ipv4_address: 172.35.71.6
  server1:
    build: ./Server1
    restart: always
    ports:
      - "5006:5006"
    networks:
      - db_network
      service_network:
        ipv4_address: 172.35.71.7
  server2:
    build: ./Server2
    restart: always
    ports:
      - "5007:5007"
    networks:
      - db_network
      service_network:
        ipv4_address: 172.35.71.8
  server3:
    build: ./Server3
    restart: always
    ports:
      - "5008:5008"
    networks:
      - db_network
      service_network:
        ipv4_address: 172.35.71.9
  db:
      image: mysql
      #command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 1234
      ports:
        - "3306:3306"
      networks:
        db_network:
          ipv4_address: 10.10.11.2
          
networks:
  service_network:
    driver: "bridge"
    ipam:
      config:
        - subnet: 172.35.71.0/24
        - gateway: 172.35.71.1
  db_network:
    driver: "bridge"
    ipam:
      config:
        - subnet: 10.10.11.0/24
        - gateway: 10.10.11.1              