version: "3.1"
services:
  balancer:
    build: ./Balancer
    restart: always
    ports:
      - "5005:5005"
    networks:
      mynetwork:
        ipv4_address: 172.35.71.6  
  server1:
    build: ./Server1
    restart: always
    ports:
      - "5006:5006"
    networks:
      mynetwork:
        ipv4_address: 172.35.71.7 
  server2:
    build: ./Server2
    restart: always
    ports:
      - "5007:5007"
    networks:
      mynetwork:
        ipv4_address: 172.35.71.8
  server3:
    build: ./Server3
    restart: always
    ports:
      - "5008:5008"
    networks:
      mynetwork:
        ipv4_address: 172.35.71.9
networks:
  mynetwork:
    ipam:
      config:
        - subnet: 172.35.71.0/24 
